language: python
python:
  - "3.6"

branches:
  only:
    - master

sudo: required

services:
  - docker

script:
  - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then bash check_secrets.sh; fi'
  - python tests.py
