language: python
python:
  - "3.6"

branches:
  only:
    - travis-tests

sudo: required

services:
  - docker

install:
  - pip install -r requirements.txt

script:
  - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then bash check_secrets.sh; fi'
  - python tests.py
